version: '2'
services:

  database:
    image: 'mongo'
    container_name: 'my-mongo-container'
    networks:
      zoo_example:
        aliases:
          - database
    environment:
      - MONGO_INITDB_DATABASE=zoo
      - MONGO_INITDB_ROOT_USERNAME=tiger
      - MONGO_INITDB_ROOT_PASSWORD=meow
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - '27017:27017'

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "14268:14268"
      - "16686:16686"
    networks:
      zoo_example:
        aliases:
          - jaeger

  app-service:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      zoo_example:
        aliases:
          - app-service
    command:
      - /client/client
    ports:
      - '8080:8080'
    depends_on:
      - jaeger
      - database

networks:
  zoo_example: {}
